// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qozznmvyuiiyrbmktgsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvenpubXZ5dWlpeXJibWt0Z3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MTU5NzQsImV4cCI6MjA1NzI5MTk3NH0.Q0yEI1_bYcbWTpM4AJQAzVBOb9Dxqf53LSjSDoNs408";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);