// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izidsxjebciwbjwclkju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6aWRzeGplYmNpd2Jqd2Nsa2p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MTIwNjcsImV4cCI6MjA1NzI4ODA2N30.u60E9QGJmIhAFFVLiAxBjN3ycXanr-8oVZyFwZSeDMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);